# Generated by Django 5.0.6 on 2024-05-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="host",
            field=models.CharField(default="default_host", max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="votes_to_skip",
            field=models.IntegerField(default=1),
        ),
    ]
